# Generated by Django 4.1.4 on 2023-06-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slno',
            field=models.TextField(max_length=250),
        ),
    ]
